### ISSUE TITLE
Cannot get information from server which have use port 19132

### ISSUE THREAD

**Issue by sinhpn92** [xXNurioXx/minecraft-server-pinger#6]
Hi team,
I did try to use this lib to fetch server infor of `bw.lbsg.net:19132`. But I have got error this server not online.
What's wrong here?

**Comment by nuriofernandez** [comment]
Hi @sinhpn92,

I have tried to connect to that Minecraft server and is not online.
In order to check what's happening, I need you to let that server online for testing.

Is that server blocking remote connections?
Where you have tested the `minecraft-server-pinger` library?
Does the computer where you have executed the code have access to that server port?

Let's see what's going wrong here! 👍

**Comment by sinhpn92** [comment]
Hi @xXNurioXx ,
Thank you for your response. I did check on there: `https://mcsrvstat.us/server/bw.lbsg.net:19132`
Please check.

**Comment by nuriofernandez** [comment]
Ok, with that link I can understand the problem.
This library does not support PocketMine servers yet.

📝  I'm gonna create a new task to add support to it.

Thank you for reporting this issue. 👍

**Comment by sinhpn92** [comment]
Thank @xXNurioXx,
Hope to integrate soon :D
